// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250412203456_ModifyRoutesEntities")]
    partial class ModifyRoutesEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ZAR",
                            Name = "Zaragoza"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "BCN",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "MAD",
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "VAL",
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "SEV",
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "COR",
                            Name = "Cordoba"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "MUR",
                            Name = "Murcia"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "LER",
                            Name = "Lerida"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "ALB",
                            Name = "Albacete"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "CR",
                            Name = "Ciudad Real"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "GRA",
                            Name = "Granada"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "TER",
                            Name = "Teruel"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DueStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<long>("StartCityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TruckId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("StartCityId");

                    b.HasIndex("TruckId");

                    b.ToTable("Freights");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageThreadId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2025, 4, 12, 19, 49, 55, 201, DateTimeKind.Utc).AddTicks(8524),
                            IsRead = false,
                            MessageThreadId = 1L,
                            Text = "Hey, are you available for a call?",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2025, 4, 12, 20, 4, 55, 201, DateTimeKind.Utc).AddTicks(8536),
                            IsRead = true,
                            MessageThreadId = 1L,
                            Text = "Yes, I can join in 5 minutes.",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2025, 4, 11, 20, 34, 55, 201, DateTimeKind.Utc).AddTicks(8544),
                            IsRead = false,
                            MessageThreadId = 2L,
                            Text = "The meeting has been rescheduled to tomorrow.",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateTime(2025, 4, 11, 20, 44, 55, 201, DateTimeKind.Utc).AddTicks(8555),
                            IsRead = true,
                            MessageThreadId = 2L,
                            Text = "Thanks for the update!",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Domain.Entities.MessageThread", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FromId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Teaser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ToId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("MessageThreads");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTimeOffset(new DateTime(2025, 4, 12, 20, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6278), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(2025, 4, 11, 20, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6288), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 1L,
                            Subject = "Project Kickoff",
                            Teaser = "Let's schedule a kickoff meeting for the new project.",
                            ToId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTimeOffset(new DateTime(2025, 4, 12, 18, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6309), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(2025, 4, 11, 20, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6312), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 1L,
                            Subject = "Meeting Reminder",
                            Teaser = "Don't forget about our meeting tomorrow at 10 AM.",
                            ToId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Created = new DateTimeOffset(new DateTime(2025, 4, 11, 20, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6322), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(2025, 4, 11, 20, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6324), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 1L,
                            Subject = "No Subject",
                            Teaser = "",
                            ToId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Created = new DateTimeOffset(new DateTime(2025, 4, 12, 20, 4, 55, 202, DateTimeKind.Unspecified).AddTicks(6335), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(2025, 4, 11, 20, 34, 55, 202, DateTimeKind.Unspecified).AddTicks(6338), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 1L,
                            Subject = "Follow-up on Proposal",
                            Teaser = "Please review the attached proposal document.",
                            ToId = 2L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Parcel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<long>("FreightId")
                        .HasColumnType("bigint");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FreightId");

                    b.HasIndex("OriginId");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("double precision");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint");

                    b.Property<JsonDocument>("Points")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AvgSpeed = 100.0,
                            DestinationId = 3L,
                            Distance = 320.0,
                            OriginId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AvgSpeed = 95.0,
                            DestinationId = 5L,
                            Distance = 530.0,
                            OriginId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            AvgSpeed = 90.0,
                            DestinationId = 7L,
                            Distance = 400.0,
                            OriginId = 5L
                        },
                        new
                        {
                            Id = 4L,
                            AvgSpeed = 100.0,
                            DestinationId = 4L,
                            Distance = 240.0,
                            OriginId = 7L
                        },
                        new
                        {
                            Id = 5L,
                            AvgSpeed = 100.0,
                            DestinationId = 2L,
                            Distance = 350.0,
                            OriginId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            AvgSpeed = 100.0,
                            DestinationId = 8L,
                            Distance = 150.0,
                            OriginId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            AvgSpeed = 100.0,
                            DestinationId = 1L,
                            Distance = 150.0,
                            OriginId = 8L
                        },
                        new
                        {
                            Id = 8L,
                            AvgSpeed = 90.0,
                            DestinationId = 12L,
                            Distance = 200.0,
                            OriginId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            AvgSpeed = 90.0,
                            DestinationId = 4L,
                            Distance = 250.0,
                            OriginId = 12L
                        },
                        new
                        {
                            Id = 10L,
                            AvgSpeed = 90.0,
                            DestinationId = 9L,
                            Distance = 150.0,
                            OriginId = 7L
                        },
                        new
                        {
                            Id = 11L,
                            AvgSpeed = 90.0,
                            DestinationId = 4L,
                            Distance = 170.0,
                            OriginId = 9L
                        },
                        new
                        {
                            Id = 12L,
                            AvgSpeed = 100.0,
                            DestinationId = 3L,
                            Distance = 400.0,
                            OriginId = 9L
                        },
                        new
                        {
                            Id = 13L,
                            AvgSpeed = 100.0,
                            DestinationId = 4L,
                            Distance = 240.0,
                            OriginId = 7L
                        },
                        new
                        {
                            Id = 14L,
                            AvgSpeed = 90.0,
                            DestinationId = 10L,
                            Distance = 130.0,
                            OriginId = 9L
                        },
                        new
                        {
                            Id = 15L,
                            AvgSpeed = 90.0,
                            DestinationId = 10L,
                            Distance = 180.0,
                            OriginId = 6L
                        },
                        new
                        {
                            Id = 16L,
                            AvgSpeed = 90.0,
                            DestinationId = 5L,
                            Distance = 140.0,
                            OriginId = 6L
                        },
                        new
                        {
                            Id = 17L,
                            AvgSpeed = 90.0,
                            DestinationId = 11L,
                            Distance = 200.0,
                            OriginId = 6L
                        },
                        new
                        {
                            Id = 18L,
                            AvgSpeed = 90.0,
                            DestinationId = 3L,
                            Distance = 200.0,
                            OriginId = 10L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Truck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastMaintenance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("numeric");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Plate");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Consumption = 25m,
                            LastMaintenance = new DateTime(2020, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturingDate = new DateTime(2020, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeight = 0m,
                            Mileage = 100000m,
                            Plate = "4566KLM"
                        },
                        new
                        {
                            Id = 2L,
                            Consumption = 30m,
                            LastMaintenance = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturingDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeight = 0m,
                            Mileage = 75000m,
                            Plate = "8923XYZ"
                        },
                        new
                        {
                            Id = 3L,
                            Consumption = 28m,
                            LastMaintenance = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturingDate = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeight = 0m,
                            Mileage = 120000m,
                            Plate = "5634QWE"
                        },
                        new
                        {
                            Id = 4L,
                            Consumption = 26m,
                            LastMaintenance = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturingDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeight = 0m,
                            Mileage = 95000m,
                            Plate = "1122ABC"
                        },
                        new
                        {
                            Id = 5L,
                            Consumption = 27m,
                            LastMaintenance = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufacturingDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxWeight = 0m,
                            Mileage = 80000m,
                            Plate = "7834LMN"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "alberto@gmail.com",
                            Name = "alberto",
                            Password = "root",
                            Role = 2,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "ana@gmail.com",
                            Name = "ana",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "maria@gmail.com",
                            Name = "maria",
                            Password = "root",
                            Role = 1,
                            Surname = "hernandez"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "violeta@gmail.com",
                            Name = "violeta",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "gimena@gmail.com",
                            Name = "gimena",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 6L,
                            Email = "sara@gmail.com",
                            Name = "sara",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.OwnsOne("Domain.Entities.Common.GeographicCoordinates", "Location", b1 =>
                        {
                            b1.Property<long>("CityId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.HasData(
                                new
                                {
                                    CityId = 1L,
                                    Lat = 41.648800000000001,
                                    Lon = -0.8891
                                },
                                new
                                {
                                    CityId = 2L,
                                    Lat = 41.385100000000001,
                                    Lon = 2.1734
                                },
                                new
                                {
                                    CityId = 3L,
                                    Lat = 40.416800000000002,
                                    Lon = -3.7038000000000002
                                },
                                new
                                {
                                    CityId = 4L,
                                    Lat = 39.469900000000003,
                                    Lon = -0.37630000000000002
                                },
                                new
                                {
                                    CityId = 5L,
                                    Lat = 37.389099999999999,
                                    Lon = -5.9844999999999997
                                },
                                new
                                {
                                    CityId = 6L,
                                    Lat = 37.888199999999998,
                                    Lon = -4.7793999999999999
                                },
                                new
                                {
                                    CityId = 7L,
                                    Lat = 37.992199999999997,
                                    Lon = -1.1307
                                },
                                new
                                {
                                    CityId = 8L,
                                    Lat = 41.617600000000003,
                                    Lon = 0.62
                                },
                                new
                                {
                                    CityId = 9L,
                                    Lat = 38.994300000000003,
                                    Lon = -1.8561000000000001
                                },
                                new
                                {
                                    CityId = 10L,
                                    Lat = 38.9861,
                                    Lon = -3.9268999999999998
                                },
                                new
                                {
                                    CityId = 11L,
                                    Lat = 37.18817,
                                    Lon = -3.6066699999999998
                                },
                                new
                                {
                                    CityId = 12L,
                                    Lat = 40.345300000000002,
                                    Lon = -1.1068
                                });
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.HasOne("Domain.Entities.User", "Driver")
                        .WithMany("Freights")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.City", "StartCity")
                        .WithMany()
                        .HasForeignKey("StartCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Truck", "Truck")
                        .WithMany("Freights")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("StartCity");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.MessageThread", "MessageThread")
                        .WithMany("Messages")
                        .HasForeignKey("MessageThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageThread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.MessageThread", b =>
                {
                    b.HasOne("Domain.Entities.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Domain.Entities.Parcel", b =>
                {
                    b.HasOne("Domain.Entities.City", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Freight", "Freight")
                        .WithMany("Parcels")
                        .HasForeignKey("FreightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.City", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Freight");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.HasOne("Domain.Entities.City", "Destination")
                        .WithMany("RouteDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.City", "Origin")
                        .WithMany("RouteOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("RouteDestinations");

                    b.Navigation("RouteOrigins");
                });

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("Domain.Entities.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Truck", b =>
                {
                    b.Navigation("Freights");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Freights");
                });
#pragma warning restore 612, 618
        }
    }
}
