// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250327182709_AddThreadMockData")]
    partial class AddThreadMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DueEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TruckId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TruckId");

                    b.ToTable("Freights");
                });

            modelBuilder.Entity("Domain.Entities.FreightRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FreightId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FreightId");

                    b.HasIndex("RouteId");

                    b.ToTable("FreightRoutes");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageThreadId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2025, 3, 27, 17, 42, 8, 580, DateTimeKind.Utc).AddTicks(6939),
                            IsRead = false,
                            MessageThreadId = 1L,
                            Text = "Hey, are you available for a call?",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2025, 3, 27, 17, 57, 8, 580, DateTimeKind.Utc).AddTicks(6944),
                            IsRead = true,
                            MessageThreadId = 1L,
                            Text = "Yes, I can join in 5 minutes.",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2025, 3, 26, 18, 27, 8, 580, DateTimeKind.Utc).AddTicks(6947),
                            IsRead = false,
                            MessageThreadId = 2L,
                            Text = "The meeting has been rescheduled to tomorrow.",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateTime(2025, 3, 26, 18, 37, 8, 580, DateTimeKind.Utc).AddTicks(6951),
                            IsRead = true,
                            MessageThreadId = 2L,
                            Text = "Thanks for the update!",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Domain.Entities.MessageThread", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FromId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Teaser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ToId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("MessageThreads");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTimeOffset(new DateTime(2025, 3, 27, 18, 27, 8, 580, DateTimeKind.Unspecified).AddTicks(9730), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 0L,
                            Subject = "Project Kickoff",
                            Teaser = "Let's schedule a kickoff meeting for the new project.",
                            ToId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTimeOffset(new DateTime(2025, 3, 27, 16, 27, 8, 580, DateTimeKind.Unspecified).AddTicks(9738), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 0L,
                            Subject = "Meeting Reminder",
                            Teaser = "Don't forget about our meeting tomorrow at 10 AM.",
                            ToId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Created = new DateTimeOffset(new DateTime(2025, 3, 26, 18, 27, 8, 580, DateTimeKind.Unspecified).AddTicks(9742), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 0L,
                            Subject = "No Subject",
                            Teaser = "",
                            ToId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Created = new DateTimeOffset(new DateTime(2025, 3, 27, 17, 57, 8, 580, DateTimeKind.Unspecified).AddTicks(9746), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            DeletedBy = 0L,
                            DeletedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromId = 1L,
                            LastModified = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = 0L,
                            Subject = "Follow-up on Proposal",
                            Teaser = "Please review the attached proposal document.",
                            ToId = 2L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FreightId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FreightId");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("double precision");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint");

                    b.Property<JsonDocument>("Points")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Domain.Entities.Truck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastMaintenance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxPalletsLoad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("numeric");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasAlternateKey("Plate");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Consumption = 25m,
                            Height = 0m,
                            LastMaintenance = new DateTime(2020, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 0m,
                            ManufacturingDate = new DateTime(2020, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPalletsLoad = 0,
                            Mileage = 100000m,
                            Plate = "4566KLM",
                            Width = 0m
                        },
                        new
                        {
                            Id = 2L,
                            Consumption = 30m,
                            Height = 0m,
                            LastMaintenance = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 0m,
                            ManufacturingDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPalletsLoad = 0,
                            Mileage = 75000m,
                            Plate = "8923XYZ",
                            Width = 0m
                        },
                        new
                        {
                            Id = 3L,
                            Consumption = 28m,
                            Height = 0m,
                            LastMaintenance = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 0m,
                            ManufacturingDate = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPalletsLoad = 0,
                            Mileage = 120000m,
                            Plate = "5634QWE",
                            Width = 0m
                        },
                        new
                        {
                            Id = 4L,
                            Consumption = 26m,
                            Height = 0m,
                            LastMaintenance = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 0m,
                            ManufacturingDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPalletsLoad = 0,
                            Mileage = 95000m,
                            Plate = "1122ABC",
                            Width = 0m
                        },
                        new
                        {
                            Id = 5L,
                            Consumption = 27m,
                            Height = 0m,
                            LastMaintenance = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 0m,
                            ManufacturingDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPalletsLoad = 0,
                            Mileage = 80000m,
                            Plate = "7834LMN",
                            Width = 0m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "alberto@gmail.com",
                            Name = "alberto",
                            Password = "root",
                            Role = 2,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "ana@gmail.com",
                            Name = "ana",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "maria@gmail.com",
                            Name = "maria",
                            Password = "root",
                            Role = 1,
                            Surname = "hernandez"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "violeta@gmail.com",
                            Name = "violeta",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "gimena@gmail.com",
                            Name = "gimena",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        },
                        new
                        {
                            Id = 6L,
                            Email = "sara@gmail.com",
                            Name = "sara",
                            Password = "root",
                            Role = 1,
                            Surname = "salas"
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.OwnsOne("Domain.Entities.Common.GeographicCoordinates", "Location", b1 =>
                        {
                            b1.Property<long>("CityId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.HasOne("Domain.Entities.User", "Driver")
                        .WithMany("Freights")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Truck", "Truck")
                        .WithMany("Freights")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Domain.Entities.FreightRoute", b =>
                {
                    b.HasOne("Domain.Entities.Freight", "Freight")
                        .WithMany("FreightRoutes")
                        .HasForeignKey("FreightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Route", "Route")
                        .WithMany("FreightRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freight");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.MessageThread", "MessageThread")
                        .WithMany("Messages")
                        .HasForeignKey("MessageThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageThread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.MessageThread", b =>
                {
                    b.HasOne("Domain.Entities.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Domain.Entities.Pallet", b =>
                {
                    b.HasOne("Domain.Entities.Freight", "Freight")
                        .WithMany("Pallets")
                        .HasForeignKey("FreightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freight");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.HasOne("Domain.Entities.City", "Destination")
                        .WithMany("RouteDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.City", "Origin")
                        .WithMany("RouteOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("RouteDestinations");

                    b.Navigation("RouteOrigins");
                });

            modelBuilder.Entity("Domain.Entities.Freight", b =>
                {
                    b.Navigation("FreightRoutes");

                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("Domain.Entities.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Navigation("FreightRoutes");
                });

            modelBuilder.Entity("Domain.Entities.Truck", b =>
                {
                    b.Navigation("Freights");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Freights");
                });
#pragma warning restore 612, 618
        }
    }
}
